const Router = require('koa-router')
const router = new Router()
const userNameIsExistence = require('./userNameIsExistence')
const register = require('./register')
const login = require('./login')
const logout = require('./logout')
const getCurrentUser = require('./getCurrentUser')
const getUserBrief = require('./getUserBrief')
const getUserBriefByUserId = require('./getUserBriefByUserId')
const focus = require('./focus')
const nickNameIsExistence = require('./nickNameIsExistence')

router.use('/user-provider', userNameIsExistence.routes())
router.use('/user-provider', register.routes())
router.use('/user-provider', login.routes())
router.use('/user-provider', logout.routes())
router.use('/user-provider', getCurrentUser.routes())
router.use('/user-provider', getUserBrief.routes())
router.use('/user-provider', getUserBriefByUserId.routes())
router.use('/user-provider', focus.routes())
router.use('/user-provider', nickNameIsExistence.routes())

module.exports = router
